export const CATEGORIES = [
  { id: 'all', name: 'All Products', nameBn: 'সবগুলো' },
  { id: 'featured', name: 'Featured', nameBn: 'ফিচারড' },
  { id: 'best-seller', name: 'Best Seller', nameBn: 'বেস্ট সেলার' },
  { id: 'photo-frames', name: 'Photo Frames', nameBn: 'ফটো ফ্রেম' },
  { id: 'nikah-nama', name: 'Nikah Nama', nameBn: 'নিকাহ নামা' },
  { id: 'cups', name: 'Cups', nameBn: 'মগ' },
  { id: 'plates', name: 'Plates', nameBn: 'প্লেট' },
  { id: 'files', name: 'Files', nameBn: 'ফাইল' },
  { id: 'pens', name: 'Pens', nameBn: 'কলম' },
  { id: 'scales', name: 'Scales', nameBn: 'স্কেল' },
];

export const PRODUCTS = [
  {
    id: '1',
    name: 'Customized Photo Frame',
    nameBn: 'কাস্টমাইজড ফটো ফ্রেম',
    price: 1250,
    originalPrice: 1500,
    category: 'photo-frames',
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 5,
    description: 'Beautiful custom photo frame perfect for your memories.',
  },
  {
    id: '2',
    name: 'Elegant Nikah Nama Cover',
    nameBn: 'নিকাহ নামা কভার',
    price: 2500,
    originalPrice: 3000,
    category: 'nikah-nama',
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1544716278-e513176f20b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 5,
    description: 'Premium Nikah Nama cover for your special day.',
  },
  {
    id: '3',
    name: 'Personalized Coffee Mug',
    nameBn: 'পার্সোনালাইজড কফি মগ',
    price: 450,
    originalPrice: 600,
    category: 'cups',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4,
    description: 'Custom mug for your morning coffee.',
  },
  {
    id: '4',
    name: 'Ceramic Dinner Plate Set',
    nameBn: 'সেরামিক ডিনার প্লেট সেট',
    price: 3500,
    category: 'plates',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4,
    description: 'Beautiful ceramic plates for your dining table.',
  },
  {
    id: '5',
    name: 'Premium File Folder',
    nameBn: 'প্রিমিয়াম ফাইল ফোল্ডার',
    price: 350,
    category: 'files',
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1586232702178-f044c5f4d4b7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4,
    description: 'High-quality file folders for office use.',
  },
  {
    id: '6',
    name: 'Custom Engraved Pen',
    nameBn: 'কাস্টম এনগ্রেভড কলম',
    price: 250,
    category: 'pens',
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1583484963886-cfe2bff2945f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 5,
    description: 'Elegant pen with custom engraving.',
  },
  {
    id: '7',
    name: 'Engineering Scale Set',
    nameBn: 'ইঞ্জিনিয়ারিং স্কেল সেট',
    price: 850,
    category: 'scales',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4,
    description: 'Professional engineering scale set.',
  },
  {
    id: '8',
    name: 'Wooden Photo Frame',
    nameBn: 'কাঠের ফটো ফ্রেম',
    price: 1800,
    category: 'photo-frames',
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1513519245088-0e129d6c9c07?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 5,
    description: 'Premium wooden photo frame.',
  },
];
